[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "bowshockpy"
authors = [{name = "gblazquez", email = "gblazquez@iaa.es"}]
dynamic = ["version", "description"]
